FROM python:3

RUN apt-get update && \
  apt-get install curl -y && \
  curl -sSL https://get.docker.com/ | sh && \
  apt-get install -y ssh && \
  pip install docker-compose awscli

# kubectl is required to be present in the container running the agent
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
  install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

ADD server.key /app/server.key
ADD server.crt /app/server.crt
ADD build/agent /app/agent

WORKDIR /app

CMD service ssh restart && ./agent serve
