FROM ubuntu:20.04

RUN apt-get update -y
RUN apt-get install -y ca-certificates curl git jq
RUN update-ca-certificates

# kubectl is required to be present in the container running the agent
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

# Install Semaphore toolbox
RUN curl -sL https://github.com/semaphoreci/toolbox/releases/latest/download/self-hosted-linux.tar -o toolbox.tar && \
  tar -xf toolbox.tar && \
  mv toolbox /root/.toolbox && \
  /root/.toolbox/install-toolbox && \
  echo 'source ~/.toolbox/toolbox' >> /root/.bash_profile && \
  rm toolbox.tar

# Make sure GitHub keys are in the image
RUN mkdir -p /root/.ssh && \
  curl -sL https://api.github.com/meta | jq -r '.ssh_keys[]' | sed 's/^/github.com /' | tee -a /root/.ssh/known_hosts

COPY build/agent /app/agent

CMD /app/agent start --config-file /app/config/semaphore-agent.yml
